[package]
name = "fusibile"
version = { workspace = true }
authors = { workspace = true }
categories = ["command-line-utilities", "network-programming"]
documentation = "https://docs.rs/fusibile"
edition = { workspace = true }
include = ["src/**/*", "../../LICENSE", "README.md", "../../CHANGELOG.md"]
keywords = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
rust-version = { workspace = true }
description = "A CLI to mount remote file systems locally via FUSE or Dokany"

[features]
aws-s3 = ["dep:remotefs-aws-s3"]
default = ["aws-s3", "ftp", "gcs", "kube", "smb", "ssh", "webdav"]
ftp = ["dep:remotefs-ftp"]
gcs = ["dep:remotefs-gcs", "dep:serde_json"]
kube = ["dep:remotefs-kube"]
smb = ["dep:remotefs-smb"]
ssh = ["dep:remotefs-ssh"]
webdav = ["dep:remotefs-webdav"]

[dependencies]
anyhow = { workspace = true }
argh = { workspace = true }
ctrlc = { workspace = true }
dirs = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
remotefs = { workspace = true }
remotefs-aws-s3 = { workspace = true, optional = true }
remotefs-fuse = { workspace = true }
remotefs-gcs = { workspace = true, optional = true }
remotefs-kube = { workspace = true, optional = true }
remotefs-memory = { workspace = true }
remotefs-smb = { workspace = true, optional = true, features = ["find", "pavao"] }
remotefs-ssh = { workspace = true, optional = true, features = ["find", "russh"] }
remotefs-webdav = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt"] }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["user"] }
remotefs-ftp = { workspace = true, features = ["native-tls", "native-tls-vendored"], optional = true }

[target.'cfg(windows)'.dependencies]
remotefs-ftp = { workspace = true, features = ["native-tls"], optional = true }

[[bin]]
name = "fusibile"
path = "src/main.rs"
