[package]
name = "remotefs-fuse"
version = { workspace = true }
authors = { workspace = true }
categories = { workspace = true }
documentation = "https://docs.rs/remotefs-fuse"
edition = { workspace = true }
include = ["src/**/*", "../../LICENSE", "../../README.md", "../../CHANGELOG.md"]
keywords = { workspace = true }
license = { workspace = true }
readme = "../../README.md"
repository = { workspace = true }
rust-version = { workspace = true }
description = "A FUSE Driver for remote-fs"

[lints]
workspace = true

[features]
default = []
integration-tests = []
no-log = ["log/max_level_off"]

[dependencies]
log = { workspace = true }
remotefs = { workspace = true }
seahash = { workspace = true }
tempfile = { workspace = true }

[target.'cfg(unix)'.dependencies]
fuser = { workspace = true, features = ["libfuse"] }
libc = { workspace = true }
nix = { workspace = true, features = ["fs"] }

[target.'cfg(windows)'.dependencies]
dashmap = { workspace = true }
dokan = { workspace = true }
dokan-sys = { workspace = true }
path-slash = { workspace = true }
widestring = { workspace = true }
winapi = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
pretty_assertions = { workspace = true }
remotefs-memory = { workspace = true }
serial_test = { workspace = true }

[target.'cfg(unix)'.dev-dependencies]
nix = { workspace = true, features = ["user"] }

[lib]
name = "remotefs_fuse"
path = "src/lib.rs"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
